name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Lint
      run: |
        go vet -stdmethods=false $(go list ./...)
        go install mvdan.cc/gofumpt@latest
        test -z "$(gofumpt -s -l -extra .)" || echo "Please run 'gofumpt -l -w -extra .'"
        curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh
        golangci-lint run -v
        
    - name: Test
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true

    - name: Build
      run: go build -v ./...
